### PR TITLE
XCode 10.2 and Carthage

### PR DESCRIPTION
**Pull request by odisei369**
Hey. When using new XCode 10.2 with Swift 5 I was not able to install this library as a dependency, because of the value of swift version inside `.swift-version` file, which is `3.0`.
I think it would be nice to have proper version inside this file.
Thank you for your work. This library is small and easy to use.

### CODE REVIEW

**Comment by weakfl** [comment]
`swift_version` should also be added to the podspec:
```
s.swift_version = "4.2"
```

**Comment by weakfl** [comment]
Personally I don't like commits e403d8b and 00dbf11.

Regarding e403d8b:
Why would you want to always show small and medium dots if it is not necessary?

Regarding 00dbf11:
This is also wrong imho. Why would I want to show 4 dots if I only have 3 pages for example?

**Comment by odisei369** [comment]
Didn't want to include those commits to PR(the're just my experiments with library).
Simply forgot to create separate branch for them.

**Comment by odisei369** [comment]
@weakfl regardless `5.0` inside podspec file.
I didn't migrate library to Swift 5.0. I just set proper version(which is now `4.2`) to use with Carthage. Because Carthage complained about Swift version `3.0`.
I could migrate whole project to Swift 5.0 if needed. Just let me know.

**Comment by weakfl** [comment]
@odisei369 

> I didn't migrate library to Swift 5.0. I just set proper version(which is now 4.2) to use with Carthage. Because Carthage complained about Swift version 3.0.

You're right, sorry. I edited my comment accordingly.

>  I could migrate whole project to Swift 5.0 if needed. Just let me know.

That would be great, but it's probably better to open a separate PR once the current PRs have been merged and a new release has been pushed to cocoapods by @shima11.

**Pull request merged**
