### PR TITLE
spm support

### PR DESCRIPTION
**Pull request by sahbazali**
package.swift file added for supporting spm. You can configure package file.
It is tested in my local environment.

### CODE REVIEW

**Comment by jaspermayone** [comment]
@shima11 would love to see this merged, as it is a great feature that would enable me to utilize this much needed package!

**Comment by jaspermayone** [comment]
@shima11 Sent you an email

**Comment by sahbazali** [comment]
hi @j-dogcoder, 

Until spm support will be merged, you can use forked repo https://github.com/sahbazali/FlexiblePageControl as swift package.

**Note**: I am using this repo in my project and because it is not merged, I added extra changes for my own purposes. If you want to use exact version of master you can add this repo in spm with this options;

repo: https://github.com/sahbazali/FlexiblePageControl 
dependency rule: commit -> 145a62193018004af28d01b636d6db5b14891250

**Comment by jaspermayone** [comment]
> hi @j-dogcoder,
> 
> Until spm support will be merged, you can use forked repo https://github.com/sahbazali/FlexiblePageControl as swift package.
> 
> **Note**: I am using this repo in my project and because it is not merged, I added extra changes for my own purposes. If you want to use exact version of master you can add this repo in spm with this options;
> 
> repo: https://github.com/sahbazali/FlexiblePageControl dependency rule: commit -> [145a621](https://github.com/shima11/FlexiblePageControl/commit/145a62193018004af28d01b636d6db5b14891250)

Hey @sahbazali! Thank you so much. I will take a look later today.

**Comment by sahbazali** [comment]
moved to #45, because there is additional changes.

@j-dogcoder, you can use now directly with the branch `master-spm-support` of forked repo -> `https://github.com/sahbazali/FlexiblePageControl `

I'm closing this mr because there is additional change than spm support.

**Pull request closed without merging**
