### PR TITLE
use separate displayCount variable

### LINKED ISSUE #16: displayCount is wrong if numberOfPages is changed
Example:

Set `numberOfPages` to 1, `displayCount` will be set to 1:
```swift
displayCount = min(displayCount, numberOfPages)
```

Now set `numberOfPages` to 2, `displayCount` **will remain 1**:
```swift
displayCount = min(displayCount, numberOfPages)
```

@shima11 you should probably use a separate private var for all calculations related to the `displayCount` value.

### PR DESCRIPTION
**Pull request by weakfl**
This adds a private `displayCount` var to fix #16

### CODE REVIEW

**Comment by weakfl** [comment]
@shima11 ping

**Comment by shima11** [comment]
Sorry for late.
Thank you @weakfl !!

**Comment by weakfl** [comment]
@shima11 Would be great if you could push a new release to cocoapods once the pending PRs are merged.

**Comment by shima11** [comment]
Yes! Thank you!

**Pull request merged**
